---
name: infra-galaxy-release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Publish to galaxy
        run: ansible-playbook .github/workflow-config/release.yml
          -e namespace='sean_m_sullivan'
          -e github_tag=${{ github.ref_name }}
          -e api_key=${{ secrets.ANSIBLE_GALAXY_APIKEY }}
          -e collection_repo=https://github.com/${{ github.repository }}
          --verbose --skip-tags=install,cleanup


...
