---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Yaml and Ansible Lint


on:
  pull_request:
  push:

jobs:
  pre-commit:
    uses: sean-m-sullivan/infra_git_ci_cd/.github/workflows/pre-commit.yml@main
  sanity:
    uses: sean-m-sullivan/infra_git_ci_cd/.github/workflows/sanity.yml@main
    with:
      collection_namespace: redhat_cop
      collection_name: controller_configuration
      collection_version: 1.0.0
      collection_repo: https://github.com/redhat-cop/controller_configuration/
  all_green:
    if: ${{ always() }}
    needs:
      - pre-commit
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.pre-commit.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"
...
