---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:


jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        awx_version:
          - devel
          - 22.4.0
          - 22.3.0
          - 21.13.0
          - 21.11.0
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      awx_version: ${{ matrix.awx_version }}
  release:
    needs:
      - ci_standalone
    uses: "sean-m-sullivan/ansible_collections_tooling/.github/workflows/release_pipeline_dual.yml@update_release"
    with:
      collection_namespace_1: sean_m_sullivan
      collection_namespace_2: Wilk42
      collection_name: controller_configuration
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/redhat-cop/controller_configuration/
      quay_username: redhat_cop+github_action
      collection_dependencies: awx.awx
      matrix_message: asdf
    secrets:
      collection_api_key_1: ${{ secrets.GALAXY_INFRA_KEY }}
      collection_api_key_2: ${{ secrets.GALAXY_INFRA_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      quay_token: ${{ secrets.quay_token }}
      matrix_token: ${{ secrets.matrix_token }}
...
